### ISSUE TITLE
Error installing in solidus 2.2

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus_asset_variant_options#12]
I get this error after install this extension:
/Users/mariajosegonzalesantelo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activemodel-5.0.4/lib/active_model/attribute_methods.rb:433:in `method_missing': undefined method `variants' for #<Spree::Image:0x007fec02cc2928> (NoMethodError)

Due to add this in initializers/spree.rb
Spree::Image.find_each do |image|
  if image.viewable_type == "Spree::Variant"
    image.variants << image.viewable
  end
end

Does it work with aws s3?

**Comment by spaghetticode** [comment]
Closing, as at this time Solidus 2.2 is not supported anymore.
